# Generated by Django 2.2.3 on 2021-03-23 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='descuento',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='precio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
